### ISSUE TITLE
getMember() doesn't return ID of user

### ISSUE THREAD

**Issue by cullendwilson** [IanSimpson/ss-oauth2-server#1]
$member = \DataObject::get_by_id("Member", $request->getAttributes()['oauth_user_id']);
change to:
$member = \Member::get()->filter("ID", $request->getAttributes()['oauth_user_id'])->first();

**Comment by IanSimpson** [comment]
Fixed in d4ecfe1d53ac974e01f2f60e3eeb5e3f66ebd8d5
